{ lib, pkgs, testers, self, sops-nix }:

let
  mockOtpHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
  mockSaltFile = ./fixtures/rpi-otp-derived-key-salt;

  # Keep the OTP input deterministic so the derived identities and encrypted
  # SOPS fixture are reproducible across evals and test runs.
  mockRpiOtpPrivateKey = pkgs.writeShellApplication {
    name = "rpi-otp-private-key";
    text = ''
      set -euo pipefail

      while [[ $# -gt 0 ]]; do
        case "$1" in
          -l|-o)
            shift 2
            ;;
          -h|--help)
            cat <<'EOF'
Usage: rpi-otp-private-key [-l WORDS] [-o OFFSET]
EOF
            exit 0
            ;;
          --)
            shift
            break
            ;;
          *)
            shift
            ;;
        esac
      done

      printf '%s\n' '${mockOtpHex}'
    '';
  };

  derivedKeyPackage =
    (pkgs.callPackage ../pkgs/raspberrypi/rpi-otp-derived-key.nix {
      rpiOtpPrivateKey = mockRpiOtpPrivateKey;
    }).overrideAttrs (old: {
      meta = (old.meta or { }) // {
        platforms = lib.platforms.linux;
      };
    });

  # Encrypt the fixture with the same derived age identity that the module
  # will regenerate inside the VM.
  generatedSopsFile = pkgs.runCommand "rpi-otp-derived-key-sops-secrets.yaml" {
    nativeBuildInputs = [
      derivedKeyPackage
      pkgs.sops
    ];
  } ''
    set -euo pipefail

    identity_file="$PWD/identity.txt"
    plaintext_file="$PWD/secrets.yaml"

    rpi-otp-derived-key \
      --format age \
      --salt-file ${mockSaltFile} \
      --info age-identity \
      > "$identity_file"

    public_key="$(sed -n 's/^# public key: //p' "$identity_file")"
    test -n "$public_key"

    cat > "$plaintext_file" <<'EOF'
test_key: test_value
nested:
  test:
    file: another value
EOF

    SOPS_AGE_KEY_FILE="$identity_file" \
      sops --encrypt \
      --age "$public_key" \
      --input-type yaml \
      --output-type yaml \
      "$plaintext_file" > "$out"
  '';
in
testers.runNixOSTest {
  name = "rpi-otp-derived-key-sops-nix";

  nodes.machine =
    { config, lib, ... }:
    {
      imports = [
        sops-nix.nixosModules.sops
        self.nixosModules.rpi-otp-derived-key
      ];

      system.stateVersion = "25.11";
      boot.initrd.systemd.enable = true;
      boot.kernelPackages = pkgs.linuxPackages_latest;
      boot.initrd.systemd.storePaths = [
        pkgs.coreutils
        pkgs.gnugrep
      ];

      sops = {
        useSystemdActivation = true;
        # The encrypted SOPS file is generated by a derivation above, so this
        # test validates decryption at runtime instead of pre-validating a
        # checked-in store path during evaluation.
        validateSopsFiles = false;
        defaultSopsFile = generatedSopsFile;
        defaultSopsFormat = "yaml";
        age.keyFile = config.services.rpiOtpDerivedKey.secrets.age.path;
        secrets.test_key = { };
        secrets."nested/test/file" = { };
      };

      users.groups.alice = { };
      users.users.alice = {
        isSystemUser = true;
        group = "alice";
      };

      users.groups.bob = { };
      users.users.bob = {
        isSystemUser = true;
        group = "bob";
      };

      services.rpiOtpDerivedKey = {
        enable = true;
        package = derivedKeyPackage;
        initrdStorePaths = [ mockRpiOtpPrivateKey ];
        generateSalt = false;
        saltFile = "/run/rpi-otp-derived-key/salt";
        # Mirror the common initrd pattern: have the module project the shared
        # salt into /run via boot.initrd.secrets so the derived key can be
        # generated during the initrd systemd phase.
        initrdSaltSource = mockSaltFile;
        secrets.age = {
          # Generate the age identity in initrd, then keep using the same
          # /run/age-keys.txt in stage 2 so sops-nix can decrypt secrets with
          # no extra provisioning step.
          format = "age";
          info = "age-identity";
          path = "/run/age-keys.txt";
          neededForBoot = true;
          before = [ "initrd-otp-consumer.service" ];
        };
        secrets.user-owned = {
          # This second secret checks the per-user ownership and access model.
          format = "hex";
          info = "user-owned";
          owner = "alice";
        };
      };

      # Prove a boot.initrd.systemd consumer can use the derived key before
      # switch-root, and leave behind a stamp that stage 2 can verify.
      boot.initrd.systemd.services.initrd-otp-consumer = {
        wantedBy = [ "initrd.target" ];
        requires = [ "rpi-otp-derived-key-age.service" ];
        after = [ "rpi-otp-derived-key-age.service" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          set -euo pipefail

          ${pkgs.gnugrep}/bin/grep -q '^AGE-SECRET-KEY-' /run/age-keys.txt
          ${pkgs.coreutils}/bin/cp /run/age-keys.txt /run/initrd-derived-age-keys.txt
        '';
      };
    };

  testScript = ''
    start_all()

    machine.wait_for_unit("rpi-otp-derived-key-user\\x2downed.service")
    machine.wait_for_unit("sops-install-secrets.service")
    machine.wait_for_unit("sysinit.target")

    # First prove initrd systemd consumed the derived key and left it available
    # for stage 2, then confirm sops-nix can decrypt with that same identity.
    machine.succeed("cmp /run/age-keys.txt /run/initrd-derived-age-keys.txt")
    machine.succeed("grep -q '^# public key: age1' /run/age-keys.txt")
    machine.succeed("grep -q '^AGE-SECRET-KEY-' /run/age-keys.txt")
    machine.succeed("cat /run/secrets/test_key | grep -q 'test_value'")
    machine.succeed("cat /run/secrets/nested/test/file | grep -q 'another value'")

    # Then prove per-secret ownership is enforced for non-root users.
    machine.succeed("stat -c '%U %G %a' /run/rpi-otp-derived-key/user-owned | grep -q '^alice alice 400$'")
    machine.succeed("su -s /bin/sh alice -c 'cat /run/rpi-otp-derived-key/user-owned >/dev/null'")
    machine.fail("su -s /bin/sh bob -c 'cat /run/rpi-otp-derived-key/user-owned >/dev/null'")
  '';
}
