{ lib, pkgs, testers, self, sops-nix }:

let
  mockOtpHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
  mockSaltFile = ./fixtures/rpi-otp-derived-key-salt;

  # Keep the OTP input deterministic so the derived identities and encrypted
  # SOPS fixture are reproducible across evals and test runs.
  mockRpiOtpPrivateKey = pkgs.writeShellApplication {
    name = "rpi-otp-private-key";
    text = ''
            set -euo pipefail

            while [[ $# -gt 0 ]]; do
              case "$1" in
                -l|-o)
                  shift 2
                  ;;
                -h|--help)
                  cat <<'EOF'
      Usage: rpi-otp-private-key [-l WORDS] [-o OFFSET]
      EOF
                  exit 0
                  ;;
                --)
                  shift
                  break
                  ;;
                *)
                  shift
                  ;;
              esac
            done

            printf '%s\n' '${mockOtpHex}'
    '';
  };

  derivedKeyPackage =
    (pkgs.callPackage ../pkgs/raspberrypi/rpi-otp-derived-key.nix {
      rpiOtpPrivateKey = mockRpiOtpPrivateKey;
    }).overrideAttrs (old: {
      meta = (old.meta or { }) // {
        platforms = lib.platforms.linux;
      };
    });

  # Encrypt the fixture with the same derived age identity that the module
  # will regenerate inside the VM.
  generatedSopsFile = pkgs.runCommand "rpi-otp-derived-key-sops-secrets.yaml"
    {
      nativeBuildInputs = [
        derivedKeyPackage
        pkgs.sops
      ];
    } ''
        set -euo pipefail

        identity_file="$PWD/identity.txt"
        plaintext_file="$PWD/secrets.yaml"

        rpi-otp-derived-key \
          --format age \
          --salt-file ${mockSaltFile} \
          > "$identity_file"

        public_key="$(sed -n 's/^# public key: //p' "$identity_file")"
        test -n "$public_key"

        cat > "$plaintext_file" <<'EOF'
    test_key: test_value
    nested:
      test:
        file: another value
    EOF

        SOPS_AGE_KEY_FILE="$identity_file" \
          sops --encrypt \
          --age "$public_key" \
          --input-type yaml \
          --output-type yaml \
          "$plaintext_file" > "$out"
  '';
in
testers.runNixOSTest {
  name = "rpi-otp-derived-key-sops-nix";

  nodes.initrd =
    { config, ... }:
    {
      imports = [
        sops-nix.nixosModules.sops
        self.nixosModules.rpi-otp-derived-key
      ];

      system.stateVersion = "25.11";
      boot.initrd.systemd.enable = true;
      boot.kernelPackages = pkgs.linuxPackages_latest;
      boot.initrd.systemd.storePaths = [
        pkgs.coreutils
        pkgs.gnugrep
      ];

      sops = {
        useSystemdActivation = true;
        # The encrypted SOPS file is generated by a derivation above, so this
        # test validates decryption at runtime instead of pre-validating a
        # checked-in store path during evaluation.
        validateSopsFiles = false;
        defaultSopsFile = generatedSopsFile;
        defaultSopsFormat = "yaml";
        age.keyFile = config.services.rpiOtpDerivedKey.secrets.age.path;
        secrets.test_key = { };
        secrets."nested/test/file" = { };
      };

      users.groups.alice = { };
      users.users.alice = {
        isSystemUser = true;
        group = "alice";
      };

      users.groups.bob = { };
      users.users.bob = {
        isSystemUser = true;
        group = "bob";
      };

      services.rpiOtpDerivedKey = {
        enable = true;
        package = derivedKeyPackage;
        initrdStorePaths = [ mockRpiOtpPrivateKey ];
        generateSalt = false;
        saltFile = "/run/rpi-otp-derived-key/salt";
        # Mirror the common initrd pattern: have the module project the shared
        # salt into /run via boot.initrd.secrets so the derived key can be
        # generated during the initrd systemd phase.
        initrdSaltSource = mockSaltFile;
        secrets.age = {
          # Generate the age identity in initrd, then keep using the same
          # /run/age-keys.txt in stage 2 so sops-nix can decrypt secrets with
          # no extra provisioning step.
          format = "age";
          path = "/run/age-keys.txt";
          neededForBoot = true;
          before = [ "initrd-otp-consumer.service" ];
        };
        secrets.user-owned = {
          # This second secret checks the per-user ownership and access model.
          format = "hex";
          owner = "alice";
        };
      };

      # Prove a boot.initrd.systemd consumer can use the derived key before
      # switch-root, and leave behind a stamp that stage 2 can verify.
      boot.initrd.systemd.services.initrd-otp-consumer = {
        wantedBy = [ "initrd.target" ];
        requires = [ "rpi-otp-derived-key-age.service" ];
        after = [ "rpi-otp-derived-key-age.service" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        script = ''
          set -euo pipefail

          ${pkgs.gnugrep}/bin/grep -q '^AGE-SECRET-KEY-' /run/age-keys.txt
          ${pkgs.coreutils}/bin/cp /run/age-keys.txt /run/initrd-derived-age-keys.txt
        '';
      };
    };

  nodes.stage2 =
    { config, lib, ... }:
    {
      imports = [
        sops-nix.nixosModules.sops
        self.nixosModules.rpi-otp-derived-key
      ];

      system.stateVersion = "25.11";

      sops = {
        useSystemdActivation = true;
        validateSopsFiles = false;
        defaultSopsFile = generatedSopsFile;
        defaultSopsFormat = "yaml";
        age.keyFile = config.services.rpiOtpDerivedKey.secrets.age.path;
        secrets.test_key = { };
        secrets."nested/test/file" = { };
      };

      users.groups.alice = { };
      users.users.alice = {
        isSystemUser = true;
        group = "alice";
      };

      users.groups.bob = { };
      users.users.bob = {
        isSystemUser = true;
        group = "bob";
      };

      services.rpiOtpDerivedKey = {
        enable = true;
        package = derivedKeyPackage;
        secrets.age = {
          format = "age";
          path = "/run/age-keys.txt";
        };
        secrets.user-owned = {
          format = "hex";
          owner = "alice";
          path = "/var/lib/rpi-otp-derived-key/user-owned";
        };
      };

      systemd.services.sops-install-secrets.after = [ "rpi-otp-derived-key-age.service" ];

      systemd.services.rpi-otp-derived-key-salt.script = lib.mkForce ''
        set -euo pipefail

        salt_dir=/var/lib/rpi-otp-derived-key
        salt_path=/var/lib/rpi-otp-derived-key/salt

        ${pkgs.coreutils}/bin/mkdir -p "$salt_dir"

        if [[ -e "$salt_path" ]]; then
          exit 0
        fi

        tmp_path="$(${pkgs.coreutils}/bin/mktemp "$salt_dir/.rpi-otp-derived-key-salt.tmp.XXXXXX")"
        trap '${pkgs.coreutils}/bin/rm -f "$tmp_path"' EXIT

        ${pkgs.coreutils}/bin/cp ${mockSaltFile} "$tmp_path"

        ${pkgs.coreutils}/bin/chown root:root "$tmp_path"
        ${pkgs.coreutils}/bin/chmod 0400 "$tmp_path"
        ${pkgs.coreutils}/bin/mv -f "$tmp_path" "$salt_path"

        trap - EXIT
      '';
    };

  testScript = ''
    start_all()

    initrd.wait_for_unit("rpi-otp-derived-key-user\\x2downed.service")
    initrd.wait_for_unit("sops-install-secrets.service")
    initrd.wait_for_unit("sysinit.target")

    # First prove initrd systemd consumed the derived key and left it available
    # for stage 2, then confirm sops-nix can decrypt with that same identity.
    initrd.succeed("cmp /run/age-keys.txt /run/initrd-derived-age-keys.txt")
    initrd.succeed("grep -q '^# public key: age1' /run/age-keys.txt")
    initrd.succeed("grep -q '^AGE-SECRET-KEY-' /run/age-keys.txt")
    initrd.succeed("cat /run/secrets/test_key | grep -q 'test_value'")
    initrd.succeed("cat /run/secrets/nested/test/file | grep -q 'another value'")

    # Then prove per-secret ownership is enforced for non-root users.
    initrd.succeed("stat -c '%U %G %a' /run/rpi-otp-derived-key/user-owned | grep -q '^alice alice 400$'")
    initrd.succeed("su -s /bin/sh alice -c 'cat /run/rpi-otp-derived-key/user-owned >/dev/null'")
    initrd.fail("su -s /bin/sh bob -c 'cat /run/rpi-otp-derived-key/user-owned >/dev/null'")

    stage2.wait_for_unit("rpi-otp-derived-key-age.service")
    stage2.wait_for_unit("sops-install-secrets.service")
    stage2.wait_for_unit("sysinit.target")

    # Prove a consumer can order itself after the derived age identity, even
    # when the salt is created on first boot under /var/lib.
    stage2.succeed("systemctl show -P After sops-install-secrets.service | tr ' ' '\\n' | grep -qx 'rpi-otp-derived-key-age.service'")
    stage2.succeed("grep -q '^# public key: age1' /run/age-keys.txt")
    stage2.succeed("grep -q '^AGE-SECRET-KEY-' /run/age-keys.txt")
    stage2.succeed("cat /run/secrets/test_key | grep -q 'test_value'")
    stage2.succeed("cat /run/secrets/nested/test/file | grep -q 'another value'")

    # The managed salt directory becomes traversable when it also hosts a
    # non-root-readable derived secret, while the salt itself stays root-only.
    stage2.succeed("stat -c '%a %U %G' /var/lib/rpi-otp-derived-key | grep -qx '711 root root'")
    stage2.succeed("stat -c '%a %U %G' /var/lib/rpi-otp-derived-key/salt | grep -qx '400 root root'")
    stage2.succeed("stat -c '%U %G %a' /var/lib/rpi-otp-derived-key/user-owned | grep -q '^alice alice 400$'")
    stage2.succeed("su -s /bin/sh alice -c 'cat /var/lib/rpi-otp-derived-key/user-owned >/dev/null'")
    stage2.fail("su -s /bin/sh bob -c 'cat /var/lib/rpi-otp-derived-key/user-owned >/dev/null'")
    stage2.fail("su -s /bin/sh alice -c 'cat /var/lib/rpi-otp-derived-key/salt >/dev/null'")
    stage2.fail("su -s /bin/sh bob -c 'cat /var/lib/rpi-otp-derived-key/salt >/dev/null'")
  '';
}
